#!/usr/bin/env bash
SCRIPT_DIR=${BASH_SOURCE%/*}

source $SCRIPT_DIR/common/common.sh

CLUSTER_CONTEXT="{retrieved after cluster creation}"

check_setup_dependencies
check_variables
check_dependencies

case $1 in
    create)
        case $2 in
            gke-cluster)
                source $SCRIPT_DIR/common/gcloud_funcs.sh
                gcloud_guard

                GCLOUD_SERVICE_ACCOUNT="${CLUSTER_NAME}-sa"
                echo "GCloud Service Account: $GCLOUD_SERVICE_ACCOUNT"

                gcloud container clusters create --zone="$GCLOUD_ZONE" "$CLUSTER_NAME"
                gcloud_create_service_account

                GOOGLE_APPLICATION_CREDENTIALS="$SCRIPT_DIR/config/$GCLOUD_SERVICE_ACCOUNT.json"

                gcloud_create_kubeconfig
                KUBECONFIG="$SCRIPT_DIR/config/kubeconfig.yaml"

                CLUSTER_CONTEXT="$(kubectl config current-context --kubeconfig $KUBECONFIG)"
                echo ""
                echo "Using K8S Context: $CLUSTER_CONTEXT"
                echo ""

                image_registry_get_cert
                image_registry_login

                duffle_create_credentials
                duffle_relocate_build_dependencies
                duffle_create_tbs
            ;;

            *)
                echo "Specify cluster type for environment. Current options are: [gke-cluster]"
            ;;
        esac
    ;;

    delete)
        case $2 in
            gke-cluster)
                source $SCRIPT_DIR/common/gcloud_funcs.sh
                gcloud container clusters delete --zone="$GCLOUD_ZONE" "$CLUSTER_NAME" --quiet
            ;;
        *)
            echo "Specify cluster type [gke-cluster]"
            ;;
        esac
    ;;

    *)
        echo ""
        echo "Usage: pbsetup [options...]"
        echo ""
        echo -e "\tcreate - Create cluster and deploy Build Service.  Cluster types currently include [gke-cluster]"
        echo ""
        echo -e "\tdelete - Delete cluster and Build Service. Types currently include [gke-cluster]"
    ;;
esac
