#!/usr/bin/env bash
SCRIPT_DIR=${BASH_SOURCE%/*}

source $SCRIPT_DIR/common/common.sh

GCLOUD_PROJECT_ID="fe-mmcnichol"
GCLOUD_ZONE="us-central1-c"

CLUSTER_NAME="mcnichol-cluster"
CLUSTER_CONTEXT="{retrieved after cluster creation}"

IMAGE_REGISTRY_URL=""
IMAGE_REGISTRY="mcnichol"

check_dependencies

case $1 in
    create)
        case $2 in
            gke-cluster)
                gcloud_login_check

                gcloud container clusters create --zone="$GCLOUD_ZONE" "$CLUSTER_NAME"

                gcloud container clusters get-credentials "$CLUSTER_NAME" --zone="$GCLOUD_ZONE" --project="$GCLOUD_PROJECT_ID"

                CLUSTER_CONTEXT="$(kubectl config current-context)"
                echo ""
                echo "Using K8S Context: $CLUSTER_CONTEXT"
                echo ""

                image_registry_get_cert

                duffle_create_credentials

                image_registry_login

                #duffle relocate -f $SCRIPT_DIR/tmp/build-service-0.1.0.tgz -m $SCRIPT_DIR/tmp/relocated.json -p $IMAGE_REGISTRY
            ;;

            *)
                echo "Specify cluster type for environment. Current options are: [gke-cluster]"
            ;;
        esac
    ;;

    delete)
        case $2 in
            gke-cluster)
                gcloud container clusters delete --zone="$GCLOUD_ZONE" "$CLUSTER_NAME" --quiet
            ;;
        *)
            echo "Specify cluster type [gke-cluster]"
            ;;
        esac
    ;;

    *)
        echo ""
        echo "Usage: pbsetup [options...]"
        echo ""
        echo -e "\tcreate - Environment for the Build Service.  Types currently include [gke-cluster]"
        echo ""
        echo -e "\tdelete - Remove the Build Service environment. Types currently include [gke-cluster]"
    ;;
esac
