#!/usr/bin/env bash
SCRIPT_DIR=${BASH_SOURCE%/*}

source $SCRIPT_DIR/common/common.sh

GCLOUD_PROJECT_ID="fe-mmcnichol"
GCLOUD_ZONE="us-central1-c"

CLUSTER_NAME="mcnichol-cluster"
CLUSTER_CONTEXT="{retrieved after cluster creation}"

check_variables
check_dependencies

case $1 in
    create)
        case $2 in
            gke-cluster)
                source $SCRIPT_DIR/common/gcloud_funcs.sh
                gcloud_guard

                gcloud container clusters create --zone="$GCLOUD_ZONE" "$CLUSTER_NAME"
                gcloud container clusters get-credentials "$CLUSTER_NAME" --zone="$GCLOUD_ZONE" --project="$GCLOUD_PROJECT_ID"

                CLUSTER_CONTEXT="$(kubectl config current-context)"
                echo ""
                echo "Using K8S Context: $CLUSTER_CONTEXT"
                echo ""

                image_registry_get_cert
                image_registry_login

                duffle_create_credentials
                duffle_relocate_build_dependencies
            ;;

            *)
                echo "Specify cluster type for environment. Current options are: [gke-cluster]"
            ;;
        esac
    ;;

    delete)
        case $2 in
            gke-cluster)
                gcloud container clusters delete --zone="$GCLOUD_ZONE" "$CLUSTER_NAME" --quiet
            ;;
        *)
            echo "Specify cluster type [gke-cluster]"
            ;;
        esac
    ;;

    *)
        echo ""
        echo "Usage: pbsetup [options...]"
        echo ""
        echo -e "\tcreate - Create cluster and deploy Build Service.  Cluster types currently include [gke-cluster]"
        echo ""
        echo -e "\tdelete - Delete cluster and Build Service. Types currently include [gke-cluster]"
    ;;
esac
